# Generated by Django 5.1.1 on 2024-10-28 14:48

import django.db.models.deletion
import parler.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product'),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.size'),
        ),
        migrations.AddField(
            model_name='sizetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.size'),
        ),
        migrations.AlterUniqueTogether(
            name='brandtranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='product_cat_slug_93e2a7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categorytranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='colortranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='producttranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='product_rev_rating_494597_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_before_discount'], name='product_pro_price_b_785511_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_after_discount'], name='product_pro_price_a_0ed106_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_pro_categor_2b9d78_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_pro_brand_i_5d76ed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='product_pro_supplie_c098a5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created'], name='product_pro_created_998428_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['updated'], name='product_pro_updated_efcf77_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_before_discount', 'price_after_discount'], name='product_pro_price_b_c89f94_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sizetranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
