# Generated by Django 5.1.1 on 2024-11-04 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_supplie_c098a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_created_998428_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_updated_efcf77_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_price_b_c89f94_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='product_pro_id_06b227_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available'], name='product_pro_is_avai_965bdd_idx'),
        ),
    ]
