# Generated by Django 5.1.1 on 2024-11-06 08:24

from django.db import migrations, connection
from django.db.utils import ProgrammingError

def create_pg_trgm_extension(apps, schema_editor):
            pass  # Ignore errors if the extension can't be created (e.g., permission issues)

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_product_pro_supplie_c098a5_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(create_pg_trgm_extension),
    ]

