# Generated by Django 5.1.1 on 2024-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_branddimension_categorydimension_colordimension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfact',
            name='brand_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfact',
            name='category_slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfact',
            name='first_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productfact',
            name='product_name',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productfact',
            name='product_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='productfact',
            index=models.Index(fields=['category_slug', 'brand_slug', 'product_slug'], name='product_pro_categor_76ab76_idx'),
        ),
    ]
