# Generated by Django 5.1.1 on 2024-12-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_producttranslation_description"),
        ("useraccount", "0003_vendorpayoutotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="useraccount.supplierdocuments",
            ),
        ),
    ]
