# Generated by Django 5.1.1 on 2024-12-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_productfact_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfact",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productsupplier",
                to="product.product",
                verbose_name="Supplier",
            ),
        ),
    ]
