# Generated by Django 5.1.1 on 2024-12-08 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_rename_supplier_productfact_productsupplier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfact",
            name="productsupplier",
        ),
        migrations.AddField(
            model_name="productfact",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="peoductfact",
                to="product.product",
                verbose_name="Supplier",
            ),
        ),
    ]
