# Generated by Django 5.1.1 on 2024-12-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0016_alter_productfact_supplier"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productfact",
            old_name="supplier",
            new_name="supplierproduct",
        ),
    ]
