# Generated by Django 5.1.1 on 2024-10-30 17:58

import common.utils.file_upload_paths
import common.validators.image_extension_validator
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('INSTAPAY', 'Instapay'), ('VODAFONE_CASH', 'Vodafone Cash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=common.utils.file_upload_paths.payment_screenshoot_path, validators=[common.validators.image_extension_validator.image_extension_validator])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
