# Generated by Django 5.1.1 on 2024-11-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('INSTAPAY', 'Instapay'), ('VODAFONE_CASH', 'Vodafone Cash'), ('visa', 'visa')], max_length=20),
        ),
    ]
