# Generated by Django 5.1.1 on 2024-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('VODAFONE_CASH', 'Vodafone Cash'), ('CARD', 'online card')], max_length=20),
        ),
    ]
