# Generated by Django 5.1.1 on 2024-11-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_status',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('OR', 'Ordered'), ('P', 'Preparing for Shipping'), ('OTW', 'On the way'), ('DE', 'Delivered'), ('RE', 'Returned')], default='OR', max_length=10, verbose_name='Shipping Status'),
        ),
    ]
