# Generated by Django 5.1.1 on 2024-11-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payment_status_order_paymob_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('INSTAPAY', 'Instapay'), ('VODAFONE_CASH', 'Vodafone Cash'), ('ONLINE_CARD', 'online card')], max_length=20, verbose_name='Payment Method'),
        ),
    ]
