# Generated by Django 5.1.1 on 2024-11-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_payment_method'),
        ('product', '0005_auto_20241106_1024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
